'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.EntityClient
Imports System.Data.Entity.Infrastructure
Imports System.ComponentModel
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

Partial Public Class Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities")
	End Sub

	Public Sub New(ByVal connectionString As String)
		MyBase.New(connectionString)
		MyBase.Configuration.LazyLoadingEnabled = True
	End Sub

	'Public Sub New(ByVal connection As EntityConnection)
	'	MyBase.New(connection, "Entities")
	'	MyBase.ContextOptions.LazyLoadingEnabled = True
	'	OnContextCreated()
	'End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property Entries() As DbSet(Of Entry)
    Public Overridable Property Locations() As DbSet(Of Location)
    Public Overridable Property Users() As DbSet(Of User)

End Class
