'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entry
    Public Property EntryID As Long
    Public Property Amount As Nullable(Of Integer)
    Public Property EntryType As Nullable(Of Integer)
    Public Property UserID As Nullable(Of Integer)
    Public Property UserType As Nullable(Of Integer)
    Public Property Description As String
    Public Property Notes As String
    Public Property LocationID As Nullable(Of Integer)
    Public Property CategoryID As Nullable(Of Integer)
    Public Property Image As Byte()
    Public Property CreatedDate As Date
    Public Property Status As Integer

End Class
