'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Location
    Public Property LocationID As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property URL As String
    Public Property Image As Byte()
    Public Property Status As Integer

End Class
