'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property UserID As Integer
    Public Property Username As String
    Public Property Password As String
    Public Property UserType As Nullable(Of Integer)
    Public Property Name As String
    Public Property Email As String
    Public Property Phone As String
    Public Property CreatedDate As Date
    Public Property LastLogin As Date
    Public Property Status As Integer

End Class
